# Generated by Django 3.1.5 on 2021-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210128_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.CharField(default='default.jpg', max_length=512),
        ),
    ]
