# Generated by Django 3.1.5 on 2021-02-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210131_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='data',
            new_name='dia',
        ),
    ]
