# Generated by Django 3.1.5 on 2021-02-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210202_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='participantes',
            field=models.CharField(max_length=512, null='true'),
            preserve_default='true',
        ),
    ]
