# Generated by Django 3.1.5 on 2021-02-02 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jogo_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='horas',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
